/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'course-manage',
    path: '/course-manage',
    component: 'layout.base$view.course-manage',
    meta: {
      title: 'course-manage',
      i18nKey: 'route.course-manage',
      icon: 'tdesign:course'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'student-course',
    path: '/student-course',
    component: 'layout.base',
    meta: {
      title: 'student-course',
      i18nKey: 'route.student-course',
      icon: 'fluent-mdl2:publish-course'
    },
    children: [
      {
        name: 'student-course_selection',
        path: '/student-course/selection',
        component: 'view.student-course_selection',
        meta: {
          title: 'student-course_selection',
          i18nKey: 'route.student-course_selection',
          icon: 'icon-park-outline:full-selection'
        }
      }
    ]
  },
  {
    name: 'student-manage',
    path: '/student-manage',
    component: 'layout.base$view.student-manage',
    meta: {
      title: 'student-manage',
      i18nKey: 'route.student-manage',
      icon: 'hugeicons:students'
    }
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
